version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: sisyphus_postgres
    environment:
      POSTGRES_DB: sisyphus_db
      POSTGRES_USER: sisyphus_user
      POSTGRES_PASSWORD: sisyphus_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sisyphus_network

  # Redis (Optional - for task scheduling)
  redis:
    image: redis:7-alpine
    container_name: sisyphus_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sisyphus_network

  # Backend API
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: sisyphus_backend
    environment:
      - DATABASE_URL=postgresql://sisyphus_user:sisyphus_password@postgres:5432/sisyphus_db
      - REDIS_URL=redis://redis:6379
      - REDIS_ENABLED=True
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/app
    networks:
      - sisyphus_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: sisyphus_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - sisyphus_network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  sisyphus_network:
    driver: bridge 