services:
  # Backend API Service
  - type: web
    name: sisyphus-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sisyphus-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: https://sisyphus-frontend.onrender.com
      - key: REDIS_ENABLED
        value: false

  # Frontend Service
  - type: web
    name: sisyphus-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://sisyphus-backend.onrender.com

databases:
  - name: sisyphus-db
    databaseName: sisyphus_db
    user: sisyphus_user
    plan: free 